FROM openjdk:8
COPY./target/springboot-crud-hibernate-example-0.0.1-SNAPSHOT.jar springboot-crud-hibernate-example-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","springboot-crud-hibernate-example-0.0.1-SNAPSHOT"]